paths:
  /admin/rooms:
    post:
      tags:
        - admin
      summary: 공지방 생성
      description: 공지방 생성
      operationId: createRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_id:
                  type: string
                  description: 관리자 id
                room_image:
                  type: string
                  description: 공지방 이미지 url
                admin_nickname:
                  type: string
                  description: 관리자 닉네임
                room_name:
                  type: string
                  description: 공지방 이름
                room_password:
                  type: string
                  description: 공지방 비밀번호
                max_penalty:
                  type: number
                  description: 최대 페널티 개수
      responses:
        "200":
          description: 공지방 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "공지방 생성 성공!"
                  result:
                    type: object
                    properties:
                      roomImage:
                        type: string
                        description: 공지방 이미지 url
                      adminNickname:
                        type: string
                        description: 운영진 닉네임
                      roomName:
                        type: string
                        description: 공지방 이름
                      roomPassword:
                        type: string
                        description: 공지방 비밀번호
                      maxPenalty:
                        type: number
                        description: 최대 패널티 개수
                      roomInviteUrl:
                        type: string
                        description: 초대 url
  /admin/rooms/{room_id}:
    patch:
      tags:
        - admin
      summary: 공지방 수정
      description: 공지방 수정
      operationId: updateRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: room_id
          required: true
          schema:
            type: integer
            example: 1
            description: room_Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_nickname:
                  type: string
                  description: 관리자 닉네임
                room_name:
                  type: string
                  description: 공지방 이름
                room_password:
                  type: string
                  description: 공지방 비밀번호
                room_image:
                  type: string
                  description: 공지방 이미지 url
                max_penalty:
                  type: number
                  description: 최대 페널티 개수
                id: 
                  type : number 
                  description : 수정할 공지방 ID
      responses:
        "200":
          description: 공지방 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      roomImage:
                        type: string
                        description: 공지방 이미지 url
                      adminNickname:
                        type: string
                        description: 운영진 닉네임
                      roomName:
                        type: string
                        description: 공지방 이름
                      roomPassword:
                        type: string
                        description: 공지방 비밀번호
                      maxPenalty:
                        type: number
                        description: 최대 패널티 개수
  /admin/rooms:
    delete:
      tags:
        - admin
      summary: 공지방 삭제
      description: 공지방 삭제
      operationId: deleteRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomId:
                  type: integer
                  description: 삭제할 공지방 아이디 
      responses:
        "200":
          description: 공지방 삭제 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties: 
                      roomId : 
                        type : number 
                        description : 삭제된 공지방의 Id
                    
                      

