paths:
  /admin/rooms:
    post:
      tags:
        - admin
      summary: 공지방 생성
      description: 공지방 생성
      operationId: createRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_image:
                  type: string
                  description: 공지방 이미지 url
                admin_nickname:
                  type: string
                  description: 관리자 닉네임
                room_name:
                  type: string
                  description: 공지방 이름
                room_password:
                  type: string
                  description: 공지방 비밀번호
                max_penalty:
                  type: number
                  description: 최대 페널티 개수
      responses:
        "200":
          description: 공지방 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      postId:
                        type: number
                        description: 생성된 공지방ID
                      roomImage:
                        type: string
                        description: 공지방 이미지 url
                      adminNickname:
                        type: string
                        description: 운영진 닉네임
                      roomName:
                        type: string
                        description: 공지방 이름
                      roomPassword:
                        type: string
                        description: 공지방 비밀번호
                      maxPenalty:
                        type: number
                        description: 최대 패널티 개수
                      roomInviteUrl:
                        type: string
                        description: 초대 url

    patch:
      tags:
        - admin
      summary: 공지방 삭제
      description: 공지방 삭제
      operationId: deleteRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomId:
                  type: integer
                  description: 삭제할 공지방 아이디
      responses:
        "200":
          description: 공지방 삭제 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      roomId:
                        type: number
                        description: 삭제된 공지방의 Id

  /admin/rooms/{roomId}:
    patch:
      tags:
        - admin
      summary: 공지방 수정
      description: 공지방 수정
      operationId: updateRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: roomId
          required: true
          schema:
            type: integer
            example: 1
            description: roomId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_nickname:
                  type: string
                  description: 관리자 닉네임
                room_name:
                  type: string
                  description: 공지방 이름
                room_password:
                  type: string
                  description: 공지방 비밀번호
                room_image:
                  type: string
                  description: 공지방 이미지 url
                max_penalty:
                  type: number
                  description: 최대 페널티 개수
                id:
                  type: number
                  description: 수정할 공지방 ID
      responses:
        "200":
          description: 공지방 수정 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      roomImage:
                        type: string
                        description: 공지방 이미지 url
                      adminNickname:
                        type: string
                        description: 운영진 닉네임
                      roomName:
                        type: string
                        description: 공지방 이름
                      roomPassword:
                        type: string
                        description: 공지방 비밀번호
                      maxPenalty:
                        type: number
                        description: 최대 패널티 개수

  /admin/post:
    post:
      tags:
        - admin
      summary: 공지글 생성
      description: 공지글 생성
      operationId: createPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roomId:
                  type: integer
                  description: 공지방 id
                type:
                  type: string
                  description: 공지글 타입(퀴즈/미션)
                title:
                  type: string
                  description: 공지글 제목
                content:
                  type: string
                  description: 공지글 본문
                start_date:
                  type: string
                  description: 시작 기한
                end_date:
                  type: string
                  description: 마감 기한
                question:
                  type: string
                  description: 퀴즈/미션 질문
                quiz_answer:
                  type: string
                  description: 퀴즈 답
                imgURLs:
                  type: array
                  items:
                    type: string
                    description: 이미지 URL 배열
      responses:
        "200":
          description: 공지글 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success"
                  result:
                    type: object
                    properties:
                      newPostId:
                        type: integer
                        description: 생성된 공지글 ID
                      postType:
                        type: string
                        enum: [QUIZ, MISSION]
                        description: 공지글 타입(퀴즈/미션)
                      postTitle:
                        type: string
                        description: 공지글 제목
                      postContent:
                        type: string
                        description: 공지글 본문
                      imgURLs:
                        type: string
                        description: 공지글 이미지
                      startDate:
                        type: string
                        description: 시작 기한
                      endDate:
                        type: string
                        description: 마감 기한
                      question:
                        type: string
                        description: 퀴즈/미션 질문
                      quiz_answer:
                        type: string
                        description: 퀴즈 답

    patch:
      tags:
        - admin
      summary: 공지글 삭제
      description: 공지글 삭제
      operationId: deletePost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: 삭제할 공지글 아이디
      responses:
        "200":
          description: 공지글 삭제 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      deletedPostId:
                        type: number
                        description: 삭제된 공지글의 Id

  /admin/post/{postId}:
    patch:
      tags:
        - admin
      summary: 공지글 수정
      description: 공지글 수정
      operationId: updatePost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
            example: 1
            description: postId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postDate:
                  type: object
                  properties:
                    title:
                      type: string
                      description: 공지글 제목
                    content:
                      type: string
                      description: 공지글 본문
                    start_date:
                      type: string
                      description: 시작 기한
                    end_date:
                      type: string
                      description: 마감 기한
                    question:
                      type: string
                      description: 퀴즈/미션 질문
                imgURLs:
                  type: array
                  items:
                    type: string
                    description: 추가할 이미지 URL 배열
                imgToDelete:
                  type: array
                  items:
                    type: string
                    description: 삭제할 이미지 URL 배열
      responses:
        "200":
          description: 공지글 수정 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      postTitle:
                        type: string
                        description: 공지글 제목
                      postContent:
                        type: string
                        description: 공지글 본문
                      addimgURLs:
                        type: string
                        description: 추가할 공지글 이미지
                      deleteimgURLs:
                        type: string
                        description: 삭제할 공지글 이미지
                      startDate:
                        type: string
                        description: 시작 기한
                      endDate:
                        type: string
                        description: 마감 기한
                      question:
                        type: string
                        description: 퀴즈/미션 질문

  /admin/post/{postId}/unread:
    get:
      tags:
        - admin
      summary: 공지 미확인 유저 조회
      description: 유저 미확인 유저 조회
      operationId: unReadUserList
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: 공지 미확인 유저 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      profile_image:
                        type: string
                        description: 유저 프로필 사진
                      nickname:
                        type: string
                        description: 유저 닉네임

  /admin/users:
    get:
      tags:
        - admin
      summary: 유저 검색(특정/전체)
      description: 유저 검색(특정/전체)
      operationId: userSearch
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: nickname
          required: false
          description: 사용자의 닉네임
          schema:
            type: string
            example: 제이
        - in: query
          name: roomId
          required: true
          description: 사용자가 속한 room의 ID
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: 유저 검색 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      userId:
                        type: number
                        description: 유저 아이디
                      nickname:
                        type: string
                        description: 유저 닉네임
                      profile_image:
                        type: string
                        description: 유저 프로필 사진

  /admin/profile:
    get:
      tags:
        - admin
      summary: 유저 프로필 조회
      description: 유저 프로필 조회
      operationId: getUserProfile
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: roomId
          required: true
          description: 공지방 ID
          schema:
            type: integer
            example: 6
        - in: query
          name: userId
          required: true
          description: 유저 ID
          schema:
            type: integer
            example: 1240
      responses:
        "200":
          description: 프로필 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      nickname:
                        type: string
                        description: 유저 닉네임
                      profile_image:
                        type: string
                        description: 유저 프로필 사진
                      penalty_count:
                        type: integer
                        description: 패널티 개수

  /admin/invitation/{roomId}:
    get:
      tags:
        - admin
      summary: 유저 초대
      description: 유저 초대
      operationId: userInvite
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: 유저 초대하기 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      room_image:
                        type: string
                        description: 공지방 이미지
                      room_invite_url:
                        type: string
                        description: 공지방 초대 url
                      room_name:
                        type: string
                        description: 공지방 이름
                      room_password:
                        type: string
                        description: 공지방 비밀번호
                      admin_nickname:
                        type: string
                        description: 관리자 닉네임

  /admin/rooms/user-Ban:
    delete:
      tags:
        - admin
      summary: 유저 강퇴하기
      description: 유저 강퇴하기
      operationId: userDelete
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  description: 강퇴할 유저 닉네임
                room_id:
                  type: integer
                  description: 강퇴할 유저가 속한 공지방 id
      responses:
        "200":
          description: 유저 강퇴 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      message:
                        type: string
                        example: 유저 강퇴에 성공하였습니다.
