paths:
  /admin/rooms:
    post:
      tags:
        - admin
      summary: 공지방 생성
      description: 공지방을 생성합니다.
      operationId: createRooms
      consumes:
        - application/json
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 공지방 생성 성공!
          content:
          application/json:
            schema:
              type: object
              properties:
                isSuccess:
                  type: boolean
                  example: true
                code:
                  type: integer
                  example: 200
                message:
                  type: string
                  example: "success!"
                result:
                  type: array
                  example:
                    {
                      "roomData":
                        [
                          {
                            "admin_id": "25",
                            "room_image": "http:/s3/image.jpg",
                            "admin_nickname": "제이",
                            "room_name": "My Chat Room",
                            "room_password": "password123",
                            "max_penalty": 5,
                            "roomInviteUrl": "44a44aa3",
                          },
                        ],
                    }
