paths:
  /room/fixPost:
    patch:
      tags:
        - room
      summary: 고정 공지글 등록
      description: 메인화면에 고정되는 공지글을 등록/변경합니다.
      operationId: changeFixedPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: number
      responses:
        "200":
          description: 고정 공지글 등록 성공 ^^
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 고정 공지글 등록 성공
    delete:
      tags:
        - room
      summary: 고정 공지글 삭제
      description: 고정된 공지글을 메인화면에서 제거합니다.
      operationId: deleteFixedPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 고정 공지글 삭제 성공 ^^
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 고정 공지글 삭제 성공

  /room/{roomId}/all:
    get:
      tags:
        - room
      summary: 공지방 내 모든 공지글 조회
      description: 공지방 입장시 모든 공지글 조회, 커서 페이지네이션
      operationId: getAllPostsinRoom
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          schema:
            type: number
          required: true
        - name: postId
          in: query
          required: false
          schema:
            properties:
              postId:
                type: number
        - name: size
          in: query
          required: false
          schema:
            properties:
              size:
                type: number
      responses:
        "200":
          description: 공지글 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: array
                    example: {
                      "postData": [
                        {
                          "postId": 3,
                          "postType": "Quiz",
                          "postTitle": "test3",
                          "postBody": "testcontent3",
                          "postImage": "url31.com",
                          "startDate": "24. 7. 27. 19:05",
                          "endDate": "24. 7. 27. 19:05",
                          "commentCount": 1,
                          "submitState": "NOT_COMPLETE",
                        },
                        {
                          "postId": 2,
                          "postType": "Mission",
                          "postTitle": "test2",
                          "postBody": "testcontent2",
                          "postImage": null,
                          "startDate": "24. 7. 27. 19:01",
                          "endDate": "24. 7. 27. 19:01",
                          "commentCount": 0,
                          "submitState": "NOT_COMPLETE",
                        },
                        {
                          "postId": 1,
                          "postType": "Quiz",
                          "postTitle": "TEST",
                          "postBody": "TESTCONTENT",
                          "postImage": "url11.com",
                          "startDate": "24. 7. 25. 04:24",
                          "endDate": "24. 7. 25. 05:24",
                          "commentCount": 5,
                          "submitState": "COMPLETE",
                        }
                    ],
                    "cursorId": 1,
                    }

  /room/{roomId}/notChecked:
    get:
      tags:
        - room
      summary: 공지방 내 완료하지 않은 공지글 조회
      description: 공지방 입장시 완료하지 않은 공지글 조회, 최신순으로 최대 3개까지
      operationId: getnotCheckedPostsinRoom
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 완료하지 않은 공지글 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: array
                    example: {
                      "posts": [
                        {
                            "roomName": "README",
                            "postId": 6,
                            "postTitle": "test6",
                            "createdAtBefore": "1분 전",
                        },
                        {
                            "roomName": "README",
                            "postId": 4,
                            "postTitle": "test4",
                            "createdAtBefore": "2개월 전",
                        },
                        {
                            "roomName": "README",
                            "postId": 3,
                            "postTitle": "test3",
                            "createdAtBefore": "4년 전",
                        }
                      ]
                    }

  /room/post/{postId}:
    get:
      tags:
        - room
      summary: 개별 공지글 상세 조회
      description: 개별 공지글 상세 조회
      operationId: getDetailedPost
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 개별 공지글 상세 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: array
                    example: {
                      "post": [
                        {
                            "postId": 1,
                            "postType": "Quiz",
                            "postTitle": "TEST",
                            "postBody": "TESTCONTENT",
                            "startDate": "24. 7. 25. 04:24",
                            "endDate": "24. 7. 25. 05:24",
                            "commentCount": 5,
                            "submitState": "complete",
                        }
                      ],
                      "imageURLs": [
                        "url11.com",
                        "url12.com",
                      ]
                    }

  /room/post/{postId}/comment:
    get:
      tags:
        - room
      summary: 공지글별 댓글 조회
      description: 공지글별 댓글 조회
      operationId: getCommentsInPost
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: number
          required: true
        - name: commentId
          in: query
          required: false
          schema:
            properties:
              commentId:
                type: number
        - name: size
          in: query
          required: false
          schema:
            properties:
              size:
                type: number
      responses:
        "200":
          description: 공지글별 댓글 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: array
                    example: {
                      "data": [
                        {
                            "commentId": 1,
                            "commentAuthorNickname": "kimroom1",
                            "commentBody": "com.con.1",
                            "createdAt": "24. 7. 27. 18:08",
                        },
                        {
                            "commentId": 3,
                            "commentAuthorNickname": "parkroom1",
                            "commentBody": "com.con.3",
                            "createdAt": "24. 7. 27. 18:09",
                        },
                        {
                            "commentId": 4,
                            "commentAuthorNickname": "leeroom1",
                            "commentBody": "com.con.4",
                            "createdAt": "24. 7. 27. 18:09",
                        },
                        {
                            "commentId": 5,
                            "commentAuthorNickname": null,
                            "commentBody": "com.con.5",
                            "createdAt": "24. 7. 27. 18:10",
                        },
                        {
                            "commentId": 7,
                            "commentAuthorNickname": "leeroom1",
                            "commentBody": "com.con.7",
                            "createdAt": "24. 7. 27. 18:11",
                        }
                      ],
                    "cursorId": 7,
                    }
    post:
      tags:
        - room
      summary: 댓글 작성
      description: 해당 공지글에 댓글 작성
      operationId: postComment
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: number
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        "200":
          description: 댓글 작성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      commentId:
                        type: number
                        description: 댓글 ID

  /room/post/comment/{commentId}:
    delete:
      tags:
        - room
      summary: 댓글 삭제
      description: 개별 댓글 삭제
      operationId: deleteComment
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: commentId
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 댓글 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      deletedCommentId:
                        type: number
                        description: 삭제처리된 댓글의 ID

  /room/post/{postId}/submit:
    get:
      tags:
        - room
      summary: 공지글 퀴즈/미션 제출 요구사항 조회 구현
      description: 공지글 퀴즈/미션 제출 요구사항 조회 구현
      operationId: getSubmitRequirements
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 퀴즈/미션 제출 요구사항 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                        id:
                          type: number
                          description: 해당 포스트 ID
                        type:
                          type: string
                          description: 해당 포스트 타입 (퀴즈/미션)
                        question:
                          type: string
                          description: 해당 포스트의 퀴즈/미션 제출 요구사항
    post:
      tags:
        - room
      summary: 공지글 퀴즈/미션 답변 및 인증사진 제출
      description: 공지글 퀴즈/미션 답변 및 인증사진 제출
      operationId: postSubmit
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: postId
          in: path
          schema:
            type: number
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: 퀴즈/미션에 제출할 답변 (퀴즈에서는 필수, 미션에서는 NULL 가능)
                imageURLs:
                  type: array
                  description: 미션에 제출할 답변 (퀴즈에서는 NULL, 미션에서는 필수)
                  example: ["https://image1.jpeg", "https://image2.jpeg", "https://image3.jpeg"]
                  items:
                    type: string    
      responses:
        "200":
          description: 제출 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                      submitId:
                        type: number
                        description: 제출 ID
                      submitState:
                        type: string
                        description: 제출 상태 (퀴즈의 경우 정답 여부에 따라 COMPLETE / NOT_COMPLETE, 미션의 경우 PENDING)

  /room/enter/{roomId}:
    get:
      tags:
        - room
      summary: 공지방 최초 입장 화면 구현
      description: 공지방 최초 입장시 공지방 정보 조회
      operationId: getRoomEntrance
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          schema:
            type: number
          required: true
      responses:
        "200":
          description: 공지방 최초 입장시 공지방 정보 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "success!"
                  result:
                    type: object
                    properties:
                        room_name:
                          type: string
                          description: 해당 공지방 이름
                        room_image:
                          type: string
                          description: 해당 공지방 이미지 URL
                        admin_nickname:
                          type: string
                          description: 해당 공지방 관리자 닉네임