paths:
  /room/fixPost:
    patch:
      tags:
        - room
      summary: 고정 공지글 등록
      description: 메인화면에 고정되는 공지글을 등록/변경합니다.
      operationId: changeFixedPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: number
      responses:
        "200":
          description: 고정 공지글 등록 성공 ^^
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 고정 공지글 등록 성공
    delete:
      tags:
        - room
      summary: 고정 공지글 삭제
      description: 고정된 공지글을 메인화면에서 제거합니다.
      operationId: deleteFixedPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 고정 공지글 삭제 성공 ^^
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 고정 공지글 삭제 성공

  room/{roomId}/all:
    get:
      tags:
        - room
      summary: 공지방 내 모든 공지글 조회
      description: 공지방 입장시 모든 공지글 조회, 커서 페이지네이션
      operationId: getAllPostsinRoom
      consumes:
        - application/json  
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          schema:
            type: number
          required: true
        - name: postId
          in: query
          required: false
          schema:
            properties:
              postId:
                type: number
        - name: paging
          in: query
          required: false
          schema:
            properties:
              size:
                type: number
      responses:
        "200":
          description: 공지글 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: success!
                  result:
                    type: array
                    example: {
                      "postData": [
                        {
                          "postId": 3,
                          "postType": "Quiz",
                          "postTitle": "test3",
                          "postBody": "testcontent3",
                          "postImage": "url31.com",
                          "startDate": "24. 7. 27. 19:05",
                          "endDate": "24. 7. 27. 19:05",
                          "commentCount": 1,
                          "submitState": "notComplete",
                        },
                        {
                          "postId": 2,
                          "postType": "Mission",
                          "postTitle": "test2",
                          "postBody": "testcontent2",
                          "postImage": null,
                          "startDate": "24. 7. 27. 19:01",
                          "endDate": "24. 7. 27. 19:01",
                          "commentCount": 0,
                          "submitState": "notComplete",
                        },
                        {
                          "postId": 1,
                          "postType": "Quiz",
                          "postTitle": "TEST",
                          "postBody": "TESTCONTENT",
                          "postImage": "url11.com",
                          "startDate": "24. 7. 25. 04:24",
                          "endDate": "24. 7. 25. 05:24",
                          "commentCount": 5,
                          "submitState": "complete",
                        }
                    ],
                    "cursorId": 1,
                    }