paths:
  /room/fixPost:
    patch:
      tags:
        - room
      summary: 고정 공지글 등록
      description: 메인화면에 고정되는 공지글을 등록/변경합니다.
      operationId: changeFixedPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: number
      responses:
        "200":
          description: 고정 공지글 등록 성공 ^^
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 고정 공지글 등록 성공
    delete:
      tags:
        - room
      summary: 고정 공지글 삭제
      description: 고정된 공지글을 메인화면에서 제거합니다.
      operationId: deleteFixedPost
      consumes:
        - application/json
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 고정 공지글 삭제 성공 ^^
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 고정 공지글 삭제 성공
