paths:
  /user/s3/upload:
    post:
      tags:
        - user
      summary: S3에 이미지 업로드
      description: S3에 이미지를 업로드하고 url을 반환합니다.
      operationId: S3
      consumes:
        - multipart/form-data
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: file
                  description: 이미지 파일
      responses:
        "200":
          description: 이미지 업로드 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "이미지 업로드 성공"
                  result:
                    type: string
                    example: "https://s3.~"
        "401":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: USER000
                  message:
                    type: string
                    example: 사용자 인증에 실패했습니다
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다.
  
  /user/create-code:
    post:
      tags:
        - user
      summary: 이메일 인증코드 생성
      description: 이메일 인증코드 생성
      operationId: create-code
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 인증할 이메일 주소
      responses:
        "200":
          description: 이메일 인증코드 생성 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "회원가입 성공"
                  result:
                    type: string
                    example: "이메일을 확인해주세요."
  
  /user/confirm-code:
    post:
      tags:
        - user
      summary: 이메일 인증코드 확인
      description: 이메일 인증코드 확인
      operationId: confirm-code
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 인증한 이메일 주소
                code:
                  type: string
                  description: 인증 코드
      responses:
        "200":
          description: 이메일 인증코드 인증 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "회원가입 성공"
                  result:
                    type: object
                    properties:
                      verified:
                        type: boolean
                        example: true

  /user/signup:
    post:
      tags:
        - user
      summary: 회원가입
      description: 회원가입
      operationId: signup
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 이름
                nickname:
                  type: string
                  description: 닉네임
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
      responses:
        "200":
          description: 회원가입 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "회원가입 성공"
                  result:
                    type: object
                    properties:
                      userId:
                        type: number
                        description: 유저 ID
                      accessToken:
                        type: string
                        description: JWT 토큰

  /user/login:
    post:
      tags:
        - user
      summary: 로그인
      description: 로그인
      operationId: login
      consumes:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
      responses:
        "200":
          description: 로그인 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "로그인 성공"
                  result:
                    type: object
                    properties:
                      userId:
                        type: number
                        description: 유저 ID
                      accessToken:
                        type: string
                        description: JWT 토큰
  
  /user:
    get:
      tags:
        - user
      summary: 내 프로필 조회 (메인)
      description: 내 프로필 조회 (메인)
      operationId: user
      consumes:
        - application/json
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 내 프로필 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "내 프로필 조회 성공"
                  result:
                    type: object
                    properties:
                      userId:
                        type: number
                        description: 유저 ID
                      name:
                        type: string
                        description: 유저 이름
                      nickname:
                        type: string
                        description: 유저 닉네임
                      email:
                        type: string
                        description: 유저 이메일
                      profileImage:
                        type: string
                        description: 유저 프로필 사진
  
  /user/fixed:
    get:
      tags:
        - user
      summary: 고정된 공지글 조회
      description: 고정된 공지글 조회
      operationId: fixed
      consumes:
        - application/json
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 고정된 공지글 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "고정된 공지글 조회 성공"
                  result:
                    type: object
                    properties:
                      postId:
                        type: number
                        description: 공지글 ID
                      title:
                        type: string
                        description: 공지글 제목
                      startDate:
                        type: string
                        description: 시작일
                      endDate:
                        type: string
                        description: 마감일

  /user/create-room:
    get:
      tags:
        - user
      summary: 내가 생성한 공지방 조회
      description: 내가 생성한 공지방 조회
      operationId: create-room
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
            description: 페이지 번호 (기본값: 1)
        - in: query
          name: pageSize
          required: false
          schema:
            type: integer
            example: 6
            description: 페이지 크기 (기본값: 6)
      responses:
        "200":
          description: 내가 생성한 공지방 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "내가 생성한 공지방 조회 성공"
                  result:
                    type: object
                    properties:
                      roomId:
                        type: number
                        description: 공지방 ID
                      roomImage:
                        type: string
                        description: 공지방 사진
                      roomName:
                        type: string
                        description: 공지방 이름
                      nickname:
                        type: string
                        description: 본인 닉네임

  /user/join-room:
    get:
      tags:
        - user
      summary: 내가 입장한 공지방 조회
      description: 내가 입장한 공지방 조회
      operationId: join-room
      consumes:
        - application/json
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
            description: 페이지 번호 (기본값: 1)
        - in: query
          name: pageSize
          required: false
          schema:
            type: integer
            example: 6
            description: 페이지 크기 (기본값: 6)
      responses:
        "200":
          description: 내가 입장한 공지방 조회 성공!
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "내가 입장한 공지방 조회 성공"
                  result:
                    type: object
                    properties:
                      roomId:
                        type: number
                        description: 공지방 ID
                      roomImage:
                        type: string
                        description: 공지방 사진
                      roomName:
                        type: string
                        description: 공지방 이름
                      nickname:
                        type: string
                        description: 본인 닉네임
