name: Node.js Dev CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행도 가능하도록 함

jobs:
  deploy:
    runs-on: ubuntu-latest # 우분투 최신 버전으로 실행

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

        # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            cd ~
            cd back-end
            fuser -k 8000/tcp || true
            git pull origin main
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
              sudo apt install -y nodejs
            fi
            if ! command -v npm &> /dev/null; then
              sudo apt install -y npm
            fi
            npm ci
            npm start
