name: Node.js Dev CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행도 가능하도록 함

jobs:
  deploy:
    runs-on: ubuntu-latest # 우분투 최신 버전으로 실행

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

        # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            cd ~
            cd back-end
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20
            node -v
            npx pm2 stop back-end > /dev/null 2>&1
            echo stop server
            git pull origin main
            echo git pull
            if ! command -v node &> /dev/null; then
              echo node install
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
              sudo apt install -y nodejs
            fi
            if ! command -v npm &> /dev/null; then
              echo npm install
              sudo apt install -y npm
            fi
            npm ci
            npx pm2 start npm --name back-end -- start > /dev/null 2>&1
            echo start server
